/*
 * This file is generated by jOOQ.
 */
package com.javatechie.crud.example.entities;


import com.javatechie.crud.example.entities.tables.ProductToCart;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in rest_api.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRODUCT_TO_CART_PRODUCTID_IDX = Internal.createIndex(DSL.name("ProductID_idx"), ProductToCart.PRODUCT_TO_CART, new OrderField[] { ProductToCart.PRODUCT_TO_CART.PRODUCTID }, false);
}
