/*
 * This file is generated by jOOQ.
 */
package com.javatechie.crud.example.entities;


import com.javatechie.crud.example.entities.tables.Cart;
import com.javatechie.crud.example.entities.tables.ProductToCart;
import com.javatechie.crud.example.entities.tables.Products;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RestApi extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rest_api</code>
     */
    public static final RestApi REST_API = new RestApi();

    /**
     * The table <code>rest_api.cart</code>.
     */
    public final Cart CART = Cart.CART;

    /**
     * The table <code>rest_api.product_to_cart</code>.
     */
    public final ProductToCart PRODUCT_TO_CART = ProductToCart.PRODUCT_TO_CART;

    /**
     * The table <code>rest_api.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * No further instances allowed
     */
    private RestApi() {
        super("rest_api", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Cart.CART,
            ProductToCart.PRODUCT_TO_CART,
            Products.PRODUCTS
        );
    }
}
