/*
 * This file is generated by jOOQ.
 */
package com.javatechie.crud.example.entities;


import com.javatechie.crud.example.entities.tables.Cart;
import com.javatechie.crud.example.entities.tables.ProductToCart;
import com.javatechie.crud.example.entities.tables.Products;


/**
 * Convenience access to all tables in rest_api.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rest_api.cart</code>.
     */
    public static final Cart CART = Cart.CART;

    /**
     * The table <code>rest_api.product_to_cart</code>.
     */
    public static final ProductToCart PRODUCT_TO_CART = ProductToCart.PRODUCT_TO_CART;

    /**
     * The table <code>rest_api.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;
}
