/*
 * This file is generated by jOOQ.
 */
package com.javatechie.crud.example.entities.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cart implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       cartid;
    private LocalDateTime orderdate;

    public Cart() {}

    public Cart(Cart value) {
        this.cartid = value.cartid;
        this.orderdate = value.orderdate;
    }

    public Cart(
        Integer       cartid,
        LocalDateTime orderdate
    ) {
        this.cartid = cartid;
        this.orderdate = orderdate;
    }

    /**
     * Getter for <code>rest_api.cart.CartID</code>.
     */
    public Integer getCartid() {
        return this.cartid;
    }

    /**
     * Setter for <code>rest_api.cart.CartID</code>.
     */
    public Cart setCartid(Integer cartid) {
        this.cartid = cartid;
        return this;
    }

    /**
     * Getter for <code>rest_api.cart.OrderDate</code>.
     */
    public LocalDateTime getOrderdate() {
        return this.orderdate;
    }

    /**
     * Setter for <code>rest_api.cart.OrderDate</code>.
     */
    public Cart setOrderdate(LocalDateTime orderdate) {
        this.orderdate = orderdate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Cart other = (Cart) obj;
        if (cartid == null) {
            if (other.cartid != null)
                return false;
        }
        else if (!cartid.equals(other.cartid))
            return false;
        if (orderdate == null) {
            if (other.orderdate != null)
                return false;
        }
        else if (!orderdate.equals(other.orderdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.cartid == null) ? 0 : this.cartid.hashCode());
        result = prime * result + ((this.orderdate == null) ? 0 : this.orderdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Cart (");

        sb.append(cartid);
        sb.append(", ").append(orderdate);

        sb.append(")");
        return sb.toString();
    }
}
