/*
 * This file is generated by jOOQ.
 */
package com.javatechie.crud.example.entities.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductToCart implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer cartid;
    private Integer productid;
    private Integer productquantity;

    public ProductToCart() {}

    public ProductToCart(ProductToCart value) {
        this.cartid = value.cartid;
        this.productid = value.productid;
        this.productquantity = value.productquantity;
    }

    public ProductToCart(
        Integer cartid,
        Integer productid,
        Integer productquantity
    ) {
        this.cartid = cartid;
        this.productid = productid;
        this.productquantity = productquantity;
    }

    /**
     * Getter for <code>rest_api.product_to_cart.CartID</code>.
     */
    public Integer getCartid() {
        return this.cartid;
    }

    /**
     * Setter for <code>rest_api.product_to_cart.CartID</code>.
     */
    public ProductToCart setCartid(Integer cartid) {
        this.cartid = cartid;
        return this;
    }

    /**
     * Getter for <code>rest_api.product_to_cart.ProductID</code>.
     */
    public Integer getProductid() {
        return this.productid;
    }

    /**
     * Setter for <code>rest_api.product_to_cart.ProductID</code>.
     */
    public ProductToCart setProductid(Integer productid) {
        this.productid = productid;
        return this;
    }

    /**
     * Getter for <code>rest_api.product_to_cart.ProductQuantity</code>.
     */
    public Integer getProductquantity() {
        return this.productquantity;
    }

    /**
     * Setter for <code>rest_api.product_to_cart.ProductQuantity</code>.
     */
    public ProductToCart setProductquantity(Integer productquantity) {
        this.productquantity = productquantity;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProductToCart other = (ProductToCart) obj;
        if (cartid == null) {
            if (other.cartid != null)
                return false;
        }
        else if (!cartid.equals(other.cartid))
            return false;
        if (productid == null) {
            if (other.productid != null)
                return false;
        }
        else if (!productid.equals(other.productid))
            return false;
        if (productquantity == null) {
            if (other.productquantity != null)
                return false;
        }
        else if (!productquantity.equals(other.productquantity))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.cartid == null) ? 0 : this.cartid.hashCode());
        result = prime * result + ((this.productid == null) ? 0 : this.productid.hashCode());
        result = prime * result + ((this.productquantity == null) ? 0 : this.productquantity.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductToCart (");

        sb.append(cartid);
        sb.append(", ").append(productid);
        sb.append(", ").append(productquantity);

        sb.append(")");
        return sb.toString();
    }
}
